import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { ethers } from 'ethers'
import { JsonRpcProvider, FallbackProvider } from '@ethersproject/providers'
import { useEffect } from 'react'

const Home: NextPage = () => {
  useEffect(() => {
    const getEthers = async () => {
      const url = 'http://127.0.0.1:8545/'
      // const providers = urls.map((url) => new JsonRpcProvider(url))
      // const fallback = new FallbackProvider(providers, 1)
      const provider = await ethers.getDefaultProvider()
      // const promise = fallback.getBlockNumber()
      console.log('provide123r', provider)
    }

    getEthers()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>chuap</main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
